inherit_from: /Users/xuhuili/Documents/SA/Relative_Pose_Estimation_With_Gravity_Prior/config/TUM_RGBD/tum_rgbd.yaml
data:
  input_path: /Users/xuhuili/datasets/TUM_RGBD-SLAM/rgbd_dataset_freiburg3_long_office_household/
  output_path: output/TUM_RGBD/rgbd_dataset_freiburg3_long_office_household/
  scene_name: rgbd_dataset_freiburg3_long_office_household
cam:  #intrinsic is different per scene in TUM
  H: 480 
  W: 640 
  fx: 535.4
  fy: 539.2
  cx: 320.1
  cy: 247.6
  crop_edge: 0
  distortion: [0, 0, 0, 0, 0]