project_name: "Relative_pose_with_gravity_prior"
dataset_name: "TUM_RGBD"
seed: 0
cam:
  depth_scale: 5000.0
  crop_edge: 16
ransac:
  rho: 0.99
  iter: 10000
  repeat: 1
  frame_start: 1
  frame_stride: 30
  frame_pairs: 50
  epsilon: 0.003
  match_threshold: 20
  max_ratio: 0.6