project_name: "Relative_pose_with_gravity_prior"
dataset_name: "ScanNet"
seed: 0
cam: 
  H: 968
  W: 1296
  fx: 1169.621094
  fy: 1167.105103
  cx: 646.295044
  cy: 489.927032
  depth_scale: 1000
  crop_edge: 0
ransac:
  rho: 0.99
  iter: 10000
  repeat: 1
frame_start: 1
frame_stride: 30
frame_pairs: 20
epsilon: 0.001
match_threshold: 10
max_ratio: 0.9
feature_type: "MSER"
