function mat = cross_product_matrix(vec)
    % Returns the cross product matrix of a 3d vector
    mat = [0,         -vec(3),     vec(2); ...
           vec(3),     0,         -vec(1); ...
          -vec(2),     vec(1),     0];
end