project_name: "Relative_pose_with_gravity_prior"
dataset_name: "Kitti"
seed: 0
cam:
  H: 376
  W: 1241
  crop_edge: 0
cam0: 
  fx: 718.856
  fy: 718.856
  cx: 607.1928
  cy: 185.2157
  T_w2c: [0, 0, 0, 1, 0, 0, 0] # (tx,ty,tz,tw,tx,ty,tz)
cam1:
  fx: 718.856
  fy: 718.856
  cx: 607.1928
  cy: 185.2157
  T_w2c: [-0.537165718864418, 0, 0, 1, 0, 0, 0] # (tx,ty,tz,tw,tx,ty,tz)
ransac:
  rho: 0.99
  iter: 10000
  repeat: 1
sample_num: 45
frame_start: 1
frame_stride: 11
frame_pairs: 3
epsilon: 0.001
match_threshold: 70
max_ratio: 0.6 
feature_type: "SIFT"
