inherit_from: /Users/xuhuili/Documents/SA/Relative_Pose_Estimation_With_Gravity_Prior/config/kitti/scannet.yaml
data:
  input_path: /Users/xuhuili/datasets/ScanNet/scene0059_00
  output_path: output/Kitti/scene0059
  sequence: 00